import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import Header from "@/components/Header";
import MobileHeader from "@/components/MobileHeader";

 

export const metadata: Metadata = {
  title: "Finance Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html data-theme="business" lang="en">
        <body
          className=''
        >
          {/* <Navbar /> */}

          <div className="flex flex-col md:flex-row">
            <div className=" md:w-2/12 w-full bg-neutral-800">
              <div className="hidden md:flex h-svh sticky top-0"> <Header /></div>
              <div className="flex md:hidden w-full fixed top-0 z-50"><MobileHeader /> </div>
            </div>
            <div className="p-2 mt-16 md:mt-0 md:w-10/12 w-full ">
              {children}
            </div>
          </div>


          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
