import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Outfit } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import Header from "@/components/Header";
import MobileHeader from "@/components/MobileHeader";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit", // exposes a CSS variable
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Finance Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html data-theme="business" lang="en">
        <body
          className=''
        >
          {/* <Navbar /> */}

          <div className="flex flex-col md:flex-row">
            <div className=" md:w-2/12 w-full bg-neutral-800">
              <div className="hidden md:flex h-svh sticky top-0"> <Header /></div>
              <div className="flex md:hidden w-full fixed top-0 z-50"><MobileHeader /> </div>
            </div>
            <div className="p-2 mt-24 md:mt-0 md:w-10/12 w-full ">
              {children}
            </div>
          </div>


          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
